language: node_js
node_js:
  - '8.11'
before_install:
  - "echo $GOOGLE_TOKEN | base64 --decode > keyfile.json"
deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
