service: k8s-docs-pr-puller

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    GH_TOKEN:
    AT_TOKEN:
    AT_TABLE:

functions:
  cron:
    handler: index.run
    events:
      - schedule: rate(5 minutes)
